### ISSUE TITLE
KeyError: 'FULL_DYNAMIC_RGB'

### ISSUE THREAD

**Issue by mdz** [mdz/python-smarttub#4]
Reported by @curt7000:

```
Unexpected error fetching smarttub data: 'FULL_DYNAMIC_RGB'
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 149, in async_refresh
self.data = await self._async_update_data()
File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 137, in _async_update_data
return await self.update_method()
File "/home/homeassistant/.homeassistant/custom_components/smarttub/controller.py", line 82, in async_update_data
data[spa.id] = await self._get_spa_data(spa)
File "/home/homeassistant/.homeassistant/custom_components/smarttub/controller.py", line 89, in _get_spa_data
status, pumps, lights = await asyncio.gather(
File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/api.py", line 188, in get_lights
return [
File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/api.py", line 189, in
SpaLight(self, **light_info)
File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/api.py", line 403, in init
self.mode = self.LightMode[properties["mode"]]
File "/usr/lib/python3.8/enum.py", line 349, in getitem
return cls.member_map[name]
KeyError: 'FULL_DYNAMIC_RGB'
```

**Comment by mdz** [comment]
@curt7000 could you send me a screenshot or something showing which lighting modes your unit supports? Prior to this report, the only ones I knew about were: `PURPLE ORANGE RED YELLOW GREEN AQUA BLUE HIGH_SPEED_COLOR_WHEEL OFF`.

I'll add `FULL_DYNAMIC_RGB` to the list, but if there are others we can fix those too

**Comment by mdz** [comment]
@curt7000 python-smarttub 0.0.19 adds this mode

**Comment by curt7000** [comment]
Tried updating api.py, deleting the integration and adding back, but everything is still unavailable.

**Comment by curt7000** [comment]
> Tried updating api.py, deleting the integration and adding back, but everything is still unavailable.

ok, tried changing light color to Blue, and everything came back.

**Comment by mdz** [comment]
Upgrading your `python-smarttub` to 0.0.19 should also resolve the issue
permanently.

**Comment by mdz** [comment]
@curt7000 if you could share more information about the lighting modes on your unit, that would be great. Mine only supports the modes above, but yours seems to have more.

**Comment by curt7000** [comment]
I have these options on the App.

![IMG_1813](https://user-images.githubusercontent.com/47297209/109857190-6fbb1600-7c28-11eb-8d2a-e9c05eb4d58d.PNG)
![IMG_1814](https://user-images.githubusercontent.com/47297209/109857206-734e9d00-7c28-11eb-867a-eb01fc162902.PNG)

**Comment by mdz** [comment]
Thanks for that. Interesting, how does the "aftermarket light kit" work?

It would be great to see the debug output from the CLI with `python -m smarttub -u email -p password -vv info --lights` (just the part after `== Lights ==` is good. If there are any modes or settings you can change on the Exterior tab, it would be helpful to see how the output changes.

**Comment by curt7000** [comment]
Apparently, I can hook up low voltage lights to the light relay board and control them.  I suppose its for a step light or surrounding ambient light.  No plan to do so.  But ... hey ... because I can ... I probably will at some point!

Here you go:

== Lights ==
DEBUG:smarttub.api:GET spas/MYSERIAL/lights successful: {'lights': [{'zone': 1, 'mode': 'OFF', 'cycleSpeed': 0, 'color': {'red': 0, 'blue': 0, 'green': 0, 'white': 0}, 'intensity': 0, 'lastUpdated': '2021-03-04T12:03:59.967Z', 'createdBy': 'SYSTEM'}, {'zone': 2, 'mode': 'FULL_DYNAMIC_RGB', 'cycleSpeed': 0, 'color': {'red': 0, 'blue': 0, 'green': 0, 'white': 0}, 'intensity': 100, 'lastUpdated': '2021-03-04T23:58:02.521Z', 'createdBy': 'SYSTEM'}]}
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/__main__.py", line 143, in <module>
    asyncio.run(main(sys.argv[1:]))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/__main__.py", line 140, in main
    await args.func(spas, args)
  File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/__main__.py", line 40, in info_command
    for light in await spa.get_lights():
  File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/api.py", line 188, in get_lights
    return [
  File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/api.py", line 189, in <listcomp>
    SpaLight(self, **light_info)
  File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/api.py", line 403, in __init__
    self.mode = self.LightMode[properties["mode"]]
  File "/usr/lib/python3.8/enum.py", line 349, in __getitem__
    return cls._member_map_[name]
KeyError: 'FULL_DYNAMIC_RGB'

**Comment by curt7000** [comment]
Just installed 2021.3.1 on my test VM, also a VENV, Ubuntu 20.04 LTS.  All entities are showing as unavailable.

**Comment by curt7000** [comment]
weird, aftermarket kit was on.  Here it is no off.

== Lights ==
DEBUG:smarttub.api:GET spas/MYSERIAL/lights successful: {'lights': [{'zone': 1, 'mode': 'OFF', 'cycleSpeed': 0, 'color': {'red': 0, 'blue': 0, 'green': 0, 'white': 0}, 'intensity': 0, 'lastUpdated': '2021-03-05T03:04:23.450Z', 'createdBy': 'SYSTEM'}, {'zone': 2, 'mode': 'OFF', 'cycleSpeed': 0, 'color': {'red': 0, 'blue': 0, 'green': 0, 'white': 0}, 'intensity': 0, 'lastUpdated': '2021-03-05T03:04:40.370Z', 'createdBy': 'SYSTEM'}]}
<SpaLight 1: OFF (R 0/G 0/B 0/W 0) @ 0>
<SpaLight 2: OFF (R 0/G 0/B 0/W 0) @ 0>

**Comment by curt7000** [comment]
and now on

== Lights ==
DEBUG:smarttub.api:GET spas/100740933/lights successful: {'lights': [{'zone': 1, 'mode': 'OFF', 'cycleSpeed': 0, 'color': {'red': 0, 'blue': 0, 'green': 0, 'white': 0}, 'intensity': 0, 'lastUpdated': '2021-03-05T03:06:14.749Z', 'createdBy': 'SYSTEM'}, {'zone': 2, 'mode': 'HIGH_SPEED_COLOR_WHEEL', 'cycleSpeed': 6, 'color': {'red': 0, 'blue': 0, 'green': 0, 'white': 0}, 'intensity': 50, 'lastUpdated': '2021-03-05T03:06:20.309Z', 'createdBy': 'SYSTEM'}]}
<SpaLight 1: OFF (R 0/G 0/B 0/W 0) @ 0>
<SpaLight 2: HIGH_SPEED_COLOR_WHEEL (R 0/G 0/B 0/W 0) @ 50>

**Comment by curt7000** [comment]
and interior lights, on, blue, 100% intensity

== Lights ==
DEBUG:smarttub.api:GET spas/100740933/lights successful: {'lights': [{'zone': 1, 'mode': 'BLUE', 'cycleSpeed': 0, 'color': {'red': 0, 'blue': 255, 'green': 0, 'white': 0}, 'intensity': 100, 'lastUpdated': '2021-03-05T03:08:22.885Z', 'createdBy': 'SYSTEM'}, {'zone': 2, 'mode': 'OFF', 'cycleSpeed': 0, 'color': {'red': 0, 'blue': 0, 'green': 0, 'white': 0}, 'intensity': 0, 'lastUpdated': '2021-03-05T03:07:07.665Z', 'createdBy': 'SYSTEM'}]}
<SpaLight 1: BLUE (R 0/G 0/B 255/W 0) @ 100>
<SpaLight 2: OFF (R 0/G 0/B 0/W 0) @ 0>

**Comment by curt7000** [comment]
No Light Entity created.

[](url)
<img width="868" alt="Screen Shot 2021-03-04 at 10 24 01 PM" src="https://user-images.githubusercontent.com/47297209/110063076-7afd6700-7d38-11eb-8f57-38a9ba8ee046.png">

**Comment by mdz** [comment]
Please open an issue on home-assistant/core about the problem you're having
with 2021.3.1. include your logs and tag me on it.

Thanks for the light info. You should be able to control both of those
lights with the current implementation once you get it working again.

**Comment by curt7000** [comment]
well ... I disabled the integration (new feature in 2021.3.1) and
re-enabled it to grab logs and the Light entities appeared!  I'll monitor
and issue a ticket if it continues.

Regardless, great work!  If you've got a Buy Me Coffee / Beer, let me know.

**Comment by mdz** [comment]
Thank you. Glad to hear it's working for now. Do open an issue if you have
further problems.
